### PR TITLE
Add support to nearly v5.14

### PR DESCRIPTION
**Pull request by supdrewin**
The original patch v5.13 unable to patch nearly kernel v5.14 has changed the file "vt.c".
One line unmatched was modified and the new data was merged so that everything is OK now.

BTW, the patched kernel `linux-cjktty` using _v5.10_ from **AUR** has been out-to-date to me.
SO I have to build sources from git.

### CODE REVIEW

**Comment by zhmars** [comment]
Hi, it seems the 32x32 font data is included in this patch. And there are some offset when applying the patch on v5.14-rc2. Could you rebase your code?

> BTW, the patched kernel linux-cjktty using v5.10 from AUR has been out-to-date to me.

It was submitted and maintained by other people. But since it is an orphaned package, please feel free to adopt it if you have interest.

**Comment by ghost** [comment]
> Hi, it seems the 32x32 font data is included in this patch.

Yes, I merge `cjktty-add-cjk32x32-font-data.patch` into this new patch.

> And there are some offset when applying the patch on v5.14-rc2. Could you rebase your code?

This diff to show where the line I modified in this patch:

``` patch
--- cjktty-5.13.patch   2021-07-23 12:07:43.466115406 +0800
+++ cjktty-5.14-rc2.patch       2021-07-22 21:11:50.000000000 +0800
@@ -214,7 +214,7 @@
 +        vc->vc_disp_ctrl = 0;
          param.vc = vc;

-         while (!tty->stopped && count) {
+         while (!tty->flow.stopped && count) {
 @@ -3490,7 +3542,7 @@ static int __init con_init(void)
                  tty_port_init(&vc->port);
                  visual_init(vc, currcons, 1);
```

In fact, I compiled v5.14
rc2 kernel with this patch sucessfully and everything is OK.

> It was submitted and maintained by other people. But since it is an orphaned package, please feel free to adopt it if you have interest.

Actually I'm new to ArchLinux😃. (Now both my desktop and laptop are running ArchLinux)

**Comment by zhmars** [comment]
> I merge cjktty-add-cjk32x32-font-data.patch into this new patch.

The 32x32 font data patch could be useful when you want a better experience on HiDPI or Retina screens. But due to its huge size(43M, uncompressed) and unnecessary for people who dont have a high resolution screen, I would like to keep it as a optional patch.

> Where the line I modified in this patch:

Did you modify the patch hunk? It works as there are no breaking changes from upstream. But for most time, we should avoid modifying them directly.

> In fact, I compiled v5.12rc2 kernel with this patch sucessfully and everything is OK.

I believe you if you mean v5.14rc2. Offsets are usually harmless. But since we are creating a patch for a new release, it should be avoided.

**Comment by ghost** [comment]
> The 32x32 font data patch could be useful when you want a better experience on HiDPI or Retina screens. But due to its huge size(43M, uncompressed) and unnecessary for people who dont have a high resolution screen, I would like to keep it as a optional patch.

Sorry to merge optional data patch into this patch, I would open a new pull next time. (It just 2.1MB while using normal xz)

> I believe you if you mean v5.14rc2. Offsets are usually harmless. But since we are creating a patch for a new release, it should be avoided.

Yes, it's v5.14. 🤐 And now rc4 is nearly.

**Pull request closed without merging**
